Repository biz-ket/bizket-server, pull requests merged in 2025-04, with the labels that each got.

#2 [NO-ISSUE] PR 유형 삭제
  .github/PULL_REQUEST_TEMPLATE.md
Labels: chore

#5 [SWYP-18] 공통 예외처리 구현
  src/main/java/com/bizket/exception/BizException.java
  src/main/java/com/bizket/exception/BizExceptionType.java
  src/main/java/com/bizket/exception/GlobalExceptionHandler.java
Labels: enhancement

#6 [SWYP-37] 공통 BaseEntity 구현
  .github/PULL_REQUEST_TEMPLATE.md
  build.gradle
  src/main/java/com/bizket/common/model/BaseEntity.java
Labels: enhancement

#7 [NO-ISSUE] release/BIZ-0.1.0 merge to main
  .github/PULL_REQUEST_TEMPLATE.md
  build.gradle
  src/main/java/com/bizket/common/dto/Response.java
  src/main/java/com/bizket/common/model/BaseEntity.java
  src/main/java/com/bizket/exception/BizException.java
  src/main/java/com/bizket/exception/BizExceptionType.java
  src/main/java/com/bizket/exception/GlobalExceptionHandler.java
Labels: release

#8 [SWYP-37] BaseEntity 수정 및 애노테이션 추가
  src/main/java/com/bizket/BizketApplication.java
  src/main/java/com/bizket/common/model/BaseEntity.java
Labels: refactoring

#9 [SWYP] 개발, 테스트 DB 설정
  .dockerignore
  .gitignore
  Dockerfile
  build.gradle
  src/main/java/com/bizket/common/dto/Response.java
  src/main/resources/application.yml
Labels: chore

#10 [SWYP-45] CI/CD 파이프라인 구축
  .github/workflows/ci-cd.yml
  Dockerfile
  build.gradle
  src/main/resources/application.yml
Labels: ci/cd

#12 [SWYP-56] 인스타그램 로그인
  build.gradle
  src/main/java/com/bizket/auth/config/SecurityConfig.java
  src/main/java/com/bizket/auth/config/SecurityConstant.java
  src/main/java/com/bizket/auth/controller/OAuthController.java
  src/main/java/com/bizket/auth/domain/InstagramToken.java
  src/main/java/com/bizket/auth/dto/AuthResponse.java
  src/main/java/com/bizket/auth/dto/InstagramCodeRequest.java
  src/main/java/com/bizket/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/com/bizket/auth/jwt/JwtExceptionHandler.java
  src/main/java/com/bizket/auth/jwt/JwtTokenProvider.java
  src/main/java/com/bizket/auth/repository/InstagramTokenRepository.java
  src/main/java/com/bizket/auth/service/AuthService.java
  src/main/java/com/bizket/auth/service/JwtService.java
  src/main/java/com/bizket/common/member/domain/Member.java
  src/main/java/com/bizket/common/member/repository/MemberRepository.java
  src/main/java/com/bizket/exception/BizExceptionType.java
  src/main/resources/application.yml
Labels: enhancement

#17 [NO-ISSUE] .env 자동 갱신 스크립트 작성
  .github/workflows/cd.yml
Labels: ci/cd

#18 [NO-ISSUE] 도커파일, CD 네트워크 추가
  .github/workflows/cd.yml
  Dockerfile
Labels: ci/cd

#19 [NO-ISSUE] wait-for-it.sh 스크립트 작성
  wait-for-it.sh
Labels: ci/cd

#20 [NO-ISSUE] 스크립트 수정
  wait-for-it.sh
Labels: chore, ci/cd

#21 [NO-ISSUE] 스크립트 수정
  wait-for-it.sh
Labels: chore, ci/cd

#22 [NO-ISSUE] 주석 제거
  wait-for-it.sh
Labels: chore, ci/cd

#23 [NO-ISSUE] 주석 제거
  wait-for-it.sh
Labels: ci/cd

#24 [NO-ISSUE] application.yml 수정
  src/main/resources/application.yml
Labels: chore, ci/cd

#25 [NO-ISSUE] application.yml 수정
  src/main/resources/application.yml
Labels: chore

#26 [NO-ISSUE] 베이스64 엔코딩 적용
  .github/workflows/cd.yml
Labels: ci/cd

#27 [NO-ISSUE] CD 스크립트 수정
  .github/workflows/cd.yml
Labels: ci/cd

#28 [NO-ISSUE] Test
  encoded.txt
Labels: ci/cd

#29 Test11
  .github/workflows/cd.yml
Labels: ci/cd

#30 Test11
  src/main/java/com/bizket/common/testcontroller.java
Labels: chore

#31 Test11
  src/main/java/com/bizket/auth/jwt/JwtTokenProvider.java
Labels: ci/cd

#32 Test11
  src/main/java/com/bizket/auth/jwt/JwtTokenProvider.java
Labels: chore

#33 Test11
  src/main/resources/application.yml
Labels: ci/cd

#35 Test11
  src/main/resources/application.yml
Labels: ci/cd

#36 Test11
  src/main/resources/application.yml
Labels: ci/cd

#37 Test11
  .github/workflows/cd.yml
  encoded.txt
Labels: ci/cd

#38 Test11
  .github/workflows/cd.yml
Labels: ci/cd

#39 Test11
  .github/workflows/cd.yml
Labels: ci/cd

#63 chore: ci-cd test
  src/main/java/com/bizket/trend/controller/TrendController.java
Labels: chore
